import corpusJson from "../data/skills-corpus.json";

/**
 * Skill retrieval (Pattern B) — every agent can pull the few skills relevant to its
 * task from the full library, instead of hardcoding methodology. v1 uses deterministic
 * term-overlap scoring over the bundled corpus (no DB / embeddings needed); a pgvector
 * semantic upgrade can swap the scorer later without changing callers.
 *
 * Corpus is generated by scripts/index-skills.mjs from goose-skills + seo-skills-seranking.
 */

export interface Skill {
  source: string;
  name: string;
  description: string;
  path: string;
  body: string;
}

export interface RetrievedSkill {
  name: string;
  source: string;
  score: number;
  body: string;
}

const CORPUS = corpusJson as Skill[];

/**
 * Direct lookup by skill name, optionally disambiguated by source. Source is required by
 * the tool→skill map because names are not unique across corpus sources (e.g.
 * seo-content-audit exists in both seranking and goose).
 */
export function getSkillByName(name: string, source?: string): Skill | undefined {
  return CORPUS.find((s) => s.name === name && (source === undefined || s.source === source));
}

const STOP = new Set([
  "the", "a", "an", "and", "or", "for", "to", "of", "in", "on", "with", "your", "you",
  "this", "that", "it", "is", "are", "be", "by", "as", "at", "from", "how", "what", "when",
  "use", "using", "via", "per", "into", "across", "their", "our", "we", "they",
]);

function tokenize(s: string): string[] {
  return s
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length >= 3 && !STOP.has(t));
}

/**
 * Score a skill against the query terms. Matches in the name weigh most, then the
 * description, then the (truncated) body — mirroring how a human skims a skill index.
 */
function scoreSkill(skill: Skill, queryTerms: Set<string>): number {
  const name = skill.name.toLowerCase();
  const desc = skill.description.toLowerCase();
  const body = skill.body.slice(0, 2000).toLowerCase();
  let score = 0;
  for (const t of queryTerms) {
    if (name.includes(t)) score += 3;
    if (desc.includes(t)) score += 2;
    if (body.includes(t)) score += 1;
  }
  return score;
}

/**
 * Retrieve the top-K skills relevant to `query`. Optionally restrict to source
 * libraries (e.g. ["seranking"]) or boost names containing a prefix (e.g. "seo-").
 */
export function retrieveSkills(
  query: string,
  opts: { k?: number; sources?: string[]; namePrefix?: string } = {},
): RetrievedSkill[] {
  const k = opts.k ?? 4;
  const terms = new Set(tokenize(query));
  if (terms.size === 0) return [];

  const pool = opts.sources ? CORPUS.filter((s) => opts.sources!.includes(s.source)) : CORPUS;

  return pool
    .map((s) => {
      let score = scoreSkill(s, terms);
      if (opts.namePrefix && s.name.startsWith(opts.namePrefix)) score += 2; // domain boost
      return { name: s.name, source: s.source, score, body: s.body };
    })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, k);
}

/**
 * Format retrieved skills into a prompt block. Each body is capped so K skills stay
 * within a sane token budget (progressive disclosure — only the relevant few load).
 */
export function formatSkillsForPrompt(skills: RetrievedSkill[], maxBodyChars = 1800): string {
  if (skills.length === 0) return "";
  const blocks = skills.map((s) => {
    const body = s.body.length > maxBodyChars ? s.body.slice(0, maxBodyChars) + "\n…(truncated)" : s.body;
    return `### Skill: ${s.name}\n${body}`;
  });
  return `\n\n── Retrieved skills (apply the relevant methodology) ──\n${blocks.join("\n\n")}`;
}

/**
 * One-call convenience: retrieve relevant skills and return a ready-to-append prompt
 * block (empty string if none). This is what agents use to become skill-aware in one line.
 */
export function skillsPromptBlock(
  query: string,
  opts: { k?: number; sources?: string[]; namePrefix?: string; maxBodyChars?: number } = {},
): string {
  const skills = retrieveSkills(query, opts);
  return formatSkillsForPrompt(skills, opts.maxBodyChars);
}
